language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
env:
  - OCAML_VERSION=4.02 PACKAGE="bisect-summary"
os:
  - linux
script:
  - bash -ex .travis-opam.sh

